project:
  type: website
  output-dir: docs
  
editor: 
  mode: source

website:
  title: "When consensus procedes the evidence"
  favicon: /icons/cat head.png
  sidebar:
    title: "Supplementary codebook"
    logo: /icons/cat.png
    style: "docked"
    search: true
    contents:
      - text: "<b>Table of contents</b>"
      - href: index.qmd
        text: Introduction
      - href: 1-citation-network.qmd
        text: Citation network 
      - href: 2-systematic-review.qmd
        text: Systematic review
      - section: "Meta-analysis"
        contents:
        - href: 3.1-prepare-meta-analysis-dataset.qmd
          text: Prepare meta-analysis dataset
        - href: 3.2-run-models.qmd
          text: Run models and plot
        - href: 3.3-publication-bias-tests.qmd
          text: Publication bias tests
        - href: 3.4-effect-size-conversions.qmd
          text: "Appendix: Effect size conversions"
      - href: 4-map.qmd
        text: Where does the evidence come from?
      - href: 5-timeline-analysis.qmd
        text: Timeline analysis
      - text: "<br>"
      - text: "<b>Funded by</b>"
      - text: "![](icons/ARC.png)"
        href: https://www.arc.gov.au/
      - text: "<br>"
      - text: "![](icons/Natural_Sciences_and_Engineering_Research_Council_Logo.png)"
        href: https://nserc-crsng.canada.ca/en
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
