---
title: "Introduction"
date: "`r Sys.Date()`"
author:
  - name: Arian D Wallach
  - name: Patricio Pereyra
  - name: Luna M Valencia Cuervo
  - name: Shinichi Nakagawa
  - name: Erick J Lundgren
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-float: true
    toc-expand: true
    toc-title: "**CONTENTS**"
    output-file: "index.html"
    # embed-resources: true
    # code-fold: true
    code-link: true
    code-tools: true
    # number-sections: false
    # bibliography: ./bib/ref.bib
    fontsize: "10"
    mainfont: "Helvetica"
    monofont: "Fira Code"
    # fontcolor: ""
    page-layout: article
    code-overflow: wrap
    df_print: paged
    theme: cosmo
    code-line-numbers: false
    grid:
      margin-width: 250px
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: "—"     # (default is ":")
  fig-prefix: Fig.     # (default is "Figure")
  tbl-prefix: Table.   # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
bibliography: references.bib
---

## How to use
This tutorial walks readers through the analyses associated with Wallach et al 2026. 'When consensus procedes the evidence.' In Submission.

This tutorial assumes a basic understanding of R. Feel free to clone or download the [repo](www.github.com/ejlundgren/cat_evidence_review.git) to interact with the code and data directly or to simply follow along here.

Note that all analyses were conducted in .R scripts in the scripts/ folder of the repo. Some of the messier data-munging steps (e.g., standardizing text, collapsing or expanding categories) is conducted in these scripts. The interactive material on this webpage focuses on the core analyses and has been copied from these scripts for clearer communication but the original scripts remain in the repo and can be evaluated instead, if that is preferred.

